const data = [
  { id: 1, skill: "HTML" },
  { id: 2, skill: "CSS" },
  { id: 3, skill: "JavaScript" },
  { id: 4, skill: "ES6+" },
  { id: 5, skill: "APIs" },
  { id: 6, skill: "Git" },
  { id: 7, skill: "GitHub" },
  { id: 8, skill: "TypeScript" },
  { id: 9, skill: "React" },
  { id: 10, skill: "React Hooks" },
  { id: 11, skill: "UX"},
  { id: 12, skill: "Markdown" },
  { id: 13, skill: "HTML metadata" },
  { id: 14, skill: "Web performance" },
  { id: 15, skill: "HTTP" },
  { id: 16, skill: "Postman" },
  { id: 17, skill: "Visual Studio Code" },
  { id: 18, skill: "Python" },
  { id: 19, skill: "Test-driven development" },
  { id: 20, skill: "Webpack" },
  { id: 21, skill: "Code refactoring" },
  { id: 22, skill: "Redux" },
  { id: 23, skill: "Coding best practices" },
  { id: 24, skill: "Unit testing" },
  { id: 25, skill: "Integration testing" },
  { id: 26, skill: "Jest" },
  { id: 27, skill: "Agile/kanban" },
  { id: 28, skill: "Jira" },
];

export default data;
